package eu.justas.geoip.rest;

import java.util.Set;
import javax.ws.rs.core.Application;

/**
 *
 * @author justas
 */
@javax.ws.rs.ApplicationPath("rest")
public class RestAppConfig extends Application {

    @Override
    public Set<Class<?>> getClasses() {
        Set<Class<?>> resources = new java.util.HashSet<Class<?>>();
        addRestResourceClasses(resources);
        return resources;
    }

    /**
     * Do not modify addRestResourceClasses() method. It is automatically re-generated by NetBeans REST support to
     * populate given list with all resources defined in the project.
     */
    private void addRestResourceClasses(Set<Class<?>> resources) {
        resources.add(eu.justas.geoip.rest.CountryFacadeREST.class);
        resources.add(eu.justas.geoip.rest.LocationFacadeREST.class);
        resources.add(eu.justas.geoip.rest.NetworkEntryFacadeREST.class);
    }
}
